services:
  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/musicbrainz
    init: true
    volumes:
      - ./:/home/python/musicbrainz
    working_dir: /home/python/musicbrainz
