services:
  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile
    image: ghcr.io/williamjacksn/pip-tools:py3.13
    init: true
    volumes:
      - ./:/home/python/musicbrainz
    working_dir: /home/python/musicbrainz

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/musicbrainz
    init: true
    volumes:
      - ./:/home/python/musicbrainz
    working_dir: /home/python/musicbrainz
